name: CI/CD Pipeline

env:
  CONFIG_REPO_NAME: argocd-course-webapp-config
  
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write  # Required for pushing to repositories

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building and testing the app..."
        # Add your actual build/test commands here

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: WebApplication1/Dockerfile
          push: true
          tags: narendra22/cicd-test-1:${{ github.sha }}

  promote-to-dev-environment:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ env.CONFIG_REPO_NAME }}
          token: ${{ secrets.GH_PAT }}  # PAT with repo permissions
          path: ${{ env.CONFIG_REPO_NAME }}
          fetch-depth: 0  # Required for proper git history

      - name: Update image tag
        working-directory: ${{ env.CONFIG_REPO_NAME }}
        run: |
          # Configure Git identity
          git config user.email "ci-bot@argocd.com"
          git config user.name "CI Bot"
          
          # Update tag in values.yaml
          sed -i "s|tag:.*|tag: ${{ github.sha }}|" helm/webapp/values.yaml
          
          # Commit and push changes
          git add helm/webapp/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin HEAD:main
