name: ci

env:
  CONFIG_REPO_NAME: argocd-course-webapp-config
on:
  push:
    branches:
      - 'main'

# Add global permissions
permissions:
  contents: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: WebApplication1/Dockerfile
          push: true
          tags: narendra22/cicd-test-1

  promote-to-dev-environment:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout config repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/${{ env.CONFIG_REPO_NAME }}
          token: ${{ secrets.GH_PAT }}
          path: ${{ env.CONFIG_REPO_NAME }}
      
      - name: Update image tag
        working-directory: ${{ env.CONFIG_REPO_NAME }}
        run: |
          sed -i "s,tag:.*,tag:\ ${{ github.sha }}," helm/webapp/values.yaml
          git add .
          git commit -m "update image tag to ${{ github.sha }}"
          git push
